//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApiKey
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ApiKey { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
    
        public virtual User User { get; set; }
    }
}
